# Generated by Django 4.0.2 on 2022-02-22 07:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('django_patch_v6_', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 22, 7, 45, 54, 873200, tzinfo=utc)),
        ),
    ]
